language: node_js
os:
- linux
node_js:
- '8'
cache:
  directories:
  - node_modules
matrix:
  fast_finish: true
script:
  - npm install
  - npm install -g ganache-cli truffle
  - docker run -d -p 8545:8545 trufflesuite/ganache-cli:latest
  - truffle test
