language: node_js
os:
- linux
node_js:
- '8'
cache:
  directories:
  - node_modules
matrix:
  fast_finish: true
script:
  - npm install
  - npm install -g ganache-cli truffle
  - set -e
  - ganache-cli 
  - sleep 5 # to make sure ganache-cli is up and running before compiling
  - rm -rf build
  - truffle compile
  - truffle migrate --reset --network development
  - truffle test
  - kill -9 $(lsof -t -i:8545)
